version: "3"

services:
  proxy:
    build:
      context: ./docker
      dockerfile: Dockerfile
    command: "native-http-proxy --port=${PORT}"
    image: golang:1.20-alpine
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}